### ISSUE TITLE
Event search on wallet error

### ISSUE THREAD

**Issue by stevencomerthornley** [kadena-io/block-explorer#51] opened 2022-05-26 01:21 UTC
Empty response with error code 0

**Comment by enobayram** [comment] 2024-01-24 09:10
Hi @stevencomerthornley, I'm closing this issue since it's probably outdated and it's not possible to reproduce based on the issue description. I'd be happy to reopen it if you're still experiencing it and are willing to provide steps to reproduce it.

**Closed by enobayram** 2024-01-24 09:10 UTC
